/*
* ============================================================================
* RDK MANAGEMENT, LLC CONFIDENTIAL AND PROPRIETARY
* ============================================================================
* This file (and its contents) are the intellectual property of RDK Management, LLC.
* It may not be used, copied, distributed or otherwise  disclosed in whole or in
* part without the express written permission of RDK Management, LLC.
* ============================================================================
* Copyright (c) 2014 RDK Management, LLC. All rights reserved.
* ============================================================================
*/

/**
* @defgroup USB_MGM RDK Usb Device Control
* @{
* @defgroup common
* @{
**/

/* 
 * The following table is are published properties by this library  
 */
 typedef enum {
//Device Level                    //sysfs attr
RUSBCTRL_PROPNAME_MANUFACTURER = 0,   //"manufacturer"
RUSBCTRL_PROPNAME_PRODUCT,        // "product"
RUSBCTRL_PROPNAME_MODEL,          // "idProduct"
RUSBCTRL_PROPNAME_VENDOR,         // "idVendor"
RUSBCTRL_PROPNAME_SERIAL,         //"serial"
// Interface Level             
RUSBCTRL_PROPNAME_DEVTYPE,        //"bInterfaceClass"
RUSBCTRL_PROPNAME_DEVSUBTYPE,     // "bInterfaceSubClass"
} rusbCtrl_propname_t;


typedef enum {
	RUSBCTRL_SUCCESS = 0,
	RUSBCTRL_FAILURE = -1
} rusbCtrl_result_t;
/*
 * The callback will beinvoked when a device of monitored type is inserted or removed.
 *
 * devId is a unique Id generated by libusbctrl. devId should be a Id that can identify
 * a USB interface. A USB device can have multiple interfaces.
 * 
 * inserted indicates of the device is inserted or removed.
 *
 * The application can use the devId to query properties of the device. 
 * It is safe to do so from callback.
 */
typedef void (*rusbCtrl_devCallback_t)(int devId, int inserted, void *cbData);

/*
 * Initiate the library to a state that it is ready to detect device
 * events and invoke callbacks. 
 * 
 * Library can be initialized multple times. But init() and term()
 * must match.
 *
 * returns RUSBCTRL_SUCCESS on success anyother value on failure.
 *
 * This must be called first. Other APIs will error otherwise.
 */
int rusbCtrl_init(void);

/*
 * Release all resources allocated. 
 */
int rusbCtrl_term();

/*
 * Allow application to listen for USB insert/remove events.
 * returns RUSBCTRL_SUCCESS on success anyother value on failure.
 * 
 * An appliction can only register 1 callback. 
 * (This constraint may be lifted in the future if needed)
 * devList is a pointer to a an array containing list of connected devices.
 * This array is allocated on the heap and must be freed by the user.
 * devListNumEntries is the number of entries in the array.
 */
int rusbCtrl_registerCallback(rusbCtrl_devCallback_t cb, void *cbData, int **devList, int *devListNumEntries);

/*
 * Returns a property value. propertyName is a set of properties published
 * by libusbCtrl (the RUSBCTRL_PROPNAME_* macros)
 * THe user is responsible to free() the value returned. *
 * On failure NULL is returned.
 */
char *rusbCtrl_getProperty(int devId, const char *propertyName);


/** @} */
/** @} */
